### ISSUE TITLE
Show the top-index and score when no search pattern is specified

### ISSUE THREAD

**Issue by vijaykiran** [wdullaer/scotty#2]
Currently running scotty without any pattern to search for returns an error:

```
error: The following required arguments were not provided:
    <TARGET>

USAGE:
    scotty search <TARGET>

For more information try --help
```

Perhaps it would be nice to show the index with score when the patter is empty (similar to `fast -s`) https://github.com/clvv/fasd#synopsis ?

**Comment by wdullaer** [comment]
I'm not a huge fan of overloading commands.
I'd rather make a `scotty list` command to dump the current index.

Scotty uses a different searching and scoring strategy than autojump and fasd: it doesn't use frequency at all, and recency is used only as a last resort tie-breaker.

**Comment by vijaykiran** [comment]
Agreed `scotty list` would be nice.
